# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/jammy64"

#  config.vm.provision "ansible" do |ansible|
#    ansible.verbose = "vvv"
#    ansible.playbook = "playbook.yml"
#    ansible.become = "true"
#  end

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus   = 2
  end

  config.vm.define "server" do |server|
    server.vm.network "private_network", ip: "192.168.11.10", virtualbox__intnet: "mynet"
    server.vm.hostname = "server.loc"

    server.vm.provision "shell", inline: <<-SHELL
	  timedatectl set-timezone Europe/Moscow
          mkdir -p ~root/.ssh
          cp ~vagrant/.ssh/auth* ~root/.ssh
	  cat /vagrant/id_ed25519.pub >> /home/vagrant/.ssh/authorized_keys
	  cat /vagrant/id_ed25519.pub >> /root/.ssh/authorized_keys
    SHELL
  end

  config.vm.define "client" do |client|
    client.vm.network "private_network", ip: "192.168.11.20", virtualbox__intnet: "mynet"
    client.vm.hostname = "client.loc"
	
    client.vm.provision "shell", inline: <<-SHELL
	  timedatectl set-timezone Europe/Moscow
          mkdir -p ~root/.ssh
          cp ~vagrant/.ssh/auth* ~root/.ssh
	  cat /vagrant/id_ed25519.pub >> /home/vagrant/.ssh/authorized_keys
	  cat /vagrant/id_ed25519.pub >> /root/.ssh/authorized_keys
    SHELL
  end

end
