MACHINES = {
  :node1 => {
        :box_name => "ubuntu/jammy64",
        :vm_name => "node1",
        :cpus => 2,
        :memory => 2048,
        :ip => "192.168.11.11",
  },
  :node2 => {
        :box_name => "ubuntu/jammy64",
        :vm_name => "node2",
        :cpus => 2,
        :memory => 2048,
        :ip => "192.168.11.12",
  },
  :barman => {
        :box_name => "ubuntu/jammy64",
        :vm_name => "barman",
        :cpus => 2,
        :memory => 2048,
        :ip => "192.168.11.13",
  },
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|
    
    config.vm.define boxname do |box|
   
      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxconfig[:vm_name]
      #box.vm.network "private_network", ip: boxconfig[:ip]
      box.vm.network("private_network", ip: boxconfig[:ip], adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "mynet")
      box.vm.provider "virtualbox" do |v|
        v.memory = boxconfig[:memory]
        v.cpus   = boxconfig[:cpus]
      end

      # Запуск ansible-playbook
      #if boxconfig[:vm_name] == "barman"
      # box.vm.provision "ansible" do |ansible|
      #  ansible.playbook = "ansible/provision.yml"
      #  ansible.inventory_path = "ansible/hosts"
      #  ansible.host_key_checking = "false"
      #  ansible.limit = "all"
      # end
      #end

      box.vm.provision "shell", inline: <<-SHELL
         timedatectl set-timezone Europe/Moscow
         mkdir -p ~root/.ssh
         cp ~vagrant/.ssh/auth* ~root/.ssh
	 cat /vagrant/id_ed25519.pub >> /home/vagrant/.ssh/authorized_keys
	 cat /vagrant/id_ed25519.pub >> /root/.ssh/authorized_keys
         #apt-get update
         #apt-get install -y vim telnet mc  
      SHELL
    end
  end
end
