# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "elabpro/redos-7"
  config.vm.network "private_network", ip: "192.168.11.10", virtualbox__intnet: "mynet"
  config.vm.provider "virtualbox" do |vb|
     vb.memory = "2048"
     vb.cpus   = 2
   end
end
