---
- hosts: all
  become: yes
  tasks:
#Установка пакетов 
  - name: install packages
    ansible.builtin.dnf:
      name:
        - bind
        - bind-utils
        - vim
        - mc
      state: latest 
      update_cache: true 

  - name: start chronyd
    ansible.builtin.service: 
      name: chronyd
      state: restarted
      enabled: true      

#Копирование файла named.zonetransfer.key на хосты с правами 0644
#Владелец файла — root, група файла — named
  - name: copy transferkey to all servers and the client
    ansible.builtin.copy:
      src: files/named.zonetransfer.key
      dest: /etc/named.zonetransfer.key
      owner: root
      group: named
      mode: 0644


#Настройка хоста ns01
- hosts: ns01
  become: yes
  tasks:
#Копирование конфигурации DNS-сервера
  - name: copy named.conf
    ansible.builtin.copy: 
      src: files/master-named.conf
      dest: /etc/named.conf 
      owner: root 
      group: named
      mode: 0640

#Копирование файлов с настроками зоны. 
#Будут скопированы все файлы, в имя которых начинается на «named.d»
  - name: copy zones
    ansible.builtin.copy: 
      src: '{{ item }}' 
      dest: /var/named/
      owner: root
      group: named 
      mode: 0660
    with_items:
      - files/named.dns.lab
      - files/named.dns.lab.client
      - files/named.dns.lab.rev
      - files/named.newdns.lab
    # with_fileglob:
    #   - files/named.dns.la*
    #   - files/named.newdns.lab

  - name: copy dynamic zone
    ansible.builtin.copy: 
      src: files/named.ddns.lab
      dest: /var/named/dynamic/
      owner: root 
      group: named 
      mode: 0660

#Копирование файла resolv.conf
  - name: copy resolv.conf to the servers
    ansible.builtin.template: 
      src: templates/servers-resolv.conf.j2
      dest: /etc/resolv.conf 
      owner: root 
      group: root
      mode: 0644

#Изменение прав каталога /etc/named
#Права 670, владелец — root, группа — named  
  - name: set /etc/named permissions
    ansible.builtin.file: 
      path: /etc/named 
      owner: root
      group: named
      mode: 0670

#Перезапуск службы Named и добавление её в автозагрузку
  - name: ensure named is running and enabled
    ansible.builtin.service: 
      name: named
      state: restarted
      enabled: yes


- hosts: ns02
  become: yes
  tasks:
  - name: copy named.conf
    ansible.builtin.copy: 
      src: files/slave-named.conf
      dest: /etc/named.conf
      owner: root
      group: named
      mode: 0640

  - name: copy resolv.conf to the servers
    ansible.builtin.template: 
      src: templates/servers-resolv.conf.j2
      dest: /etc/resolv.conf 
      owner: root 
      group: root
      mode: 0644

  - name: set /etc/named permissions
    ansible.builtin.file: 
      path: /etc/named
      owner: root
      group: named 
      mode: 0670

  - name: ensure named is running and enabled
    ansible.builtin.service: 
      name: named 
      state: restarted
      enabled: yes
   

- hosts: client,client2
  become: yes
  tasks:
  - name: copy resolv.conf to the client
    ansible.builtin.copy: 
      src: files/client-resolv.conf
      dest: /etc/resolv.conf
      owner: root
      group: root
      mode: 0644

#Копирование конфигруационного файла rndc
  - name: copy rndc conf file
    ansible.builtin.copy: 
      src: files/rndc.conf
      dest: /home/vagrant/rndc.conf
      owner: vagrant
      group: vagrant
      mode: 0644

#Настройка сообщения при входе на сервер
  - name: copy motd to the client
    ansible.builtin.copy: 
      src: files/client-motd
      dest: /etc/motd
      owner: root
      group: root
      mode: 0644