# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/22.04"

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus   = 2
  end

  config.vm.define "backup" do |backup|
    backup.vm.network "private_network", ip: "192.168.11.160", virtualbox__intnet: "mynet"
    backup.vm.hostname = "backup"

    backup.vm.disk :disk, size: "2GB", name: "extra_storage"

    backup.vm.provision "shell", inline: <<-SHELL
	  timedatectl set-timezone Europe/Moscow
      mkdir -p ~root/.ssh
      cp ~vagrant/.ssh/auth* ~root/.ssh

	  #cat /vagrant/id_ed25519.pub >> /home/vagrant/.ssh/authorized_keys
	  #cat /vagrant/id_ed25519.pub >> /root/.ssh/authorized_keys
    SHELL
  end

  config.vm.define "client" do |client|
    client.vm.network "private_network", ip: "192.168.11.150", virtualbox__intnet: "mynet"
    client.vm.hostname = "client"
	
    client.vm.provision "shell", inline: <<-SHELL
	  timedatectl set-timezone Europe/Moscow
          mkdir -p ~root/.ssh
          cp ~vagrant/.ssh/auth* ~root/.ssh

	  #cat /vagrant/id_ed25519.pub >> /home/vagrant/.ssh/authorized_keys
	  #cat /vagrant/id_ed25519.pub >> /root/.ssh/authorized_keys
    SHELL
  end

end
