# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/22.04"

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus   = 2
  end

  config.vm.define "log" do |log|
    log.vm.network "private_network", ip: "192.168.11.15", virtualbox__intnet: "mynet"
    log.vm.hostname = "log"
    log.vm.provision "shell", inline: <<-SHELL
	  #cat /vagrant/id_ed25519.pub >> /home/vagrant/.ssh/authorized_keys
	  #cat /vagrant/id_ed25519.pub >> /root/.ssh/authorized_keys
	  timedatectl set-timezone Europe/Moscow
          apt-get update
          # синхронизация времени с удаленным источником 
	  apt-get install chrony -y
          # настройка централизованного сервера сбора логов 
	  cat /vagrant/rsyslog.conf > /etc/rsyslog.conf
	  systemctl restart rsyslog
    SHELL
  end

  config.vm.define "web" do |web|
    web.vm.network "private_network", ip: "192.168.11.10", virtualbox__intnet: "mynet"
    web.vm.hostname = "web"
	
    web.vm.provision "shell", inline: <<-SHELL
	  #cat /vagrant/id_ed25519.pub >> /home/vagrant/.ssh/authorized_keys
	  #cat /vagrant/id_ed25519.pub >> /root/.ssh/authorized_keys
	  timedatectl set-timezone Europe/Moscow
	  apt-get update
	  apt-get install chrony nginx auditd -y
	  cat /vagrant/nginx.conf > /etc/nginx/nginx.conf
          # логи аудита на удаленный сервер логов 
          cat /vagrant/30-auditd.conf > /etc/rsyslog.d/30-auditd.conf
          # правила аудита 
          cat /vagrant/audit.rules > /etc/audit/rules.d/audit.rules
	  systemctl restart nginx rsyslog auditd
    SHELL
  end

  config.vm.define "other" do |other|
    other.vm.network "private_network", ip: "192.168.11.102", virtualbox__intnet: "mynet"
    other.vm.hostname = "other"
	
    other.vm.provision "shell", inline: <<-SHELL
	  #cat /vagrant/id_ed25519.pub >> /home/vagrant/.ssh/authorized_keys
	  #cat /vagrant/id_ed25519.pub >> /root/.ssh/authorized_keys
	  timedatectl set-timezone Europe/Moscow
	  apt-get update
	  apt-get install chrony -y
          # отправка всех логов на сервер
	  echo '*.* @@192.168.11.15:514' >> /etc/rsyslog.d/50-default.conf
          systemctl restart rsyslog
    SHELL
  end

end
