#!/bin/bash
INET_IFACE="enp0s3"
LAN_IFACE="enp0s8"
LO_IFACE="lo"

LAN_IP="192.168.255.13"
INET_IP="10.0.2.15"
#LO_IP="127.0.0.1"
SERVER_IP="192.168.0.2"
MYNET_IP="192.168.11.0/24"

IPTABLES="/usr/sbin/iptables"

$IPTABLES -F
$IPTABLES -t nat -F
$IPTABLES -t mangle -F
$IPTABLES -X

# Set policies
$IPTABLES -P INPUT DROP
$IPTABLES -P FORWARD DROP
#$IPTABLES -P OUTPUT DROP
$IPTABLES -P OUTPUT ACCEPT


# INPUT chain
$IPTABLES -A INPUT -p ALL -i $LO_IFACE -j ACCEPT
$IPTABLES -A INPUT -p ALL -m state --state ESTABLISHED,RELATED -j ACCEPT
$IPTABLES -A INPUT -p tcp -m state --state INVALID -j DROP
$IPTABLES -A INPUT -p ICMP -j ACCEPT
$IPTABLES -A INPUT -s $MYNET_IP -p TCP --dport 22 -j ACCEPT # vbox mynet
$IPTABLES -A INPUT -i $LAN_IFACE -p TCP --dport 80 -j ACCEPT
$IPTABLES -A INPUT -p ALL -i $LAN_IFACE -j ACCEPT

# FORWARD chain
$IPTABLES -A FORWARD -p ICMP -i $LAN_IFACE -s 0/0 -j ACCEPT
$IPTABLES -A FORWARD -i $LAN_IFACE -o $INET_IFACE -j ACCEPT
$IPTABLES -A FORWARD -p tcp --dport 80 -i $INET_IFACE  -j ACCEPT
$IPTABLES -A FORWARD -m state --state ESTABLISHED,RELATED -j ACCEPT

# OUTPUT chain
# Special OUTPUT rules to decide which IP's to allow.
#$IPTABLES -A OUTPUT -p ALL -s $LO_IP -j ACCEPT
#$IPTABLES -A OUTPUT -p ALL -s $LAN_IP -j ACCEPT
#$IPTABLES -A OUTPUT -p ALL -s $INET_IP -j ACCEPT


# nat table

# PREROUTING chain
$IPTABLES -t nat -A PREROUTING -p TCP -d $INET_IP --dport 8080 -j DNAT --to-destination $SERVER_IP:80

# POSTROUTING chain
$IPTABLES -t nat -A POSTROUTING -o $INET_IFACE -j SNAT --to-source $INET_IP
#$IPTABLES -t nat -A POSTROUTING -o $INET_IFACE -j MASQUERADE
$IPTABLES -t nat -A POSTROUTING -o $LAN_IFACE -j SNAT --to-source $LAN_IP
#$IPTABLES -t nat -A POSTROUTING -o $LAN_IFACE -j MASQUERADE