# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :hzfs => {
        :box_name => "bento/ubuntu-24.04",
        :ip_addr  => '192.168.11.101',
        :net_name => "mynet",		
    :disks => {
        :sata1 => {
            :dfile => './sata1.vdi',
            :size => 512,
            :port => 1
        },
        :sata2 => {
            :dfile => './sata2.vdi',
            :size => 512, # Megabytes
            :port => 2
        },
        :sata3 => {
            :dfile => './sata3.vdi',
            :size => 512,
            :port => 3
        },
        :sata4 => {
            :dfile => './sata4.vdi',
            :size => 512, 
            :port => 4
        },
        :sata5 => {
            :dfile => './sata5.vdi',
            :size => 512,
            :port => 5
        },
        :sata6 => {
            :dfile => './sata6.vdi',
            :size => 512,
            :port => 6
        },
        :sata7 => {
            :dfile => './sata7.vdi',
            :size => 512, 
            :port => 7
        },
        :sata8 => {
            :dfile => './sata8.vdi',
            :size => 512, 
            :port => 8
        },
    }
  },
}


Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
      config.vm.define boxname do |box|
        box.vm.box         = boxconfig[:box_name]
        box.vm.box_version = boxconfig[:box_version]
        box.vm.host_name   = "zfs"
	box.vm.network "private_network", ip: boxconfig[:ip_addr], virtualbox__intnet: boxconfig[:net_name]

        box.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "2048"]
            needsController = false

            boxconfig[:disks].each do |dname, dconf|
               unless File.exist?(dconf[:dfile])
                  vb.customize ['createhd', '--filename', dconf[:dfile], '--variant', 'Fixed', '--size', dconf[:size]]
               end
            end

            boxconfig[:disks].each do |dname, dconf|
               vb.customize ['storageattach', :id,  '--storagectl', 'SATA Controller', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]
            end
        end

        box.vm.provision "shell", inline: <<-SHELL
          apt-get install -y zfsutils-linux
          modprobe zfs
          apt-get install -y wget
          timedatectl set-timezone Europe/Moscow
          #cat /vagrant/id_ed25519.pub >> /home/vagrant/.ssh/authorized_keys
          #cat /vagrant/id_ed25519.pub >> /root/.ssh/authorized_keys
      SHELL
    end
  end
end
