# -*- mode: ruby -*-
# vim: set ft=ruby :
# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
:inetRouter => {
    :box_name => "ubuntu/22.04",
    :vm_name  => "inetRouter",
   #:public => {:ip => '10.10.10.1', :adapter => 1},
    :net  => [
		#ip, adpter, netmask, virtualbox__intnet
		["192.168.255.1", 2, "255.255.255.252", "router-net"], 
		["192.168.11.10", 8, "255.255.255.0",   "mynet"],
    ]
  },

:inetRouter2 => {
    :box_name => "ubuntu/22.04",
    :vm_name  => "inetRouter2",
    #:public   => {:ip => '10.10.10.3', :adapter => 1},
    :net => [
		["192.168.255.13", 2, "255.255.255.252", "router2-net"], 
		["192.168.11.13",  8, "255.255.255.0",   "mynet"],
  	    ]
#  ,  :forwarded_port => { :guest =>8080  , :host => 8080 }	
  },  
  
  :centralRouter => {
	:box_name => "ubuntu/22.04",
	:vm_name  => "centralRouter",
	:net => [
			   ["192.168.255.2",  2, "255.255.255.252",  "router-net"],
			   ["192.168.0.1",    3, "255.255.255.240",  "dir-net"],
			   ["192.168.255.14", 4, "255.255.255.252", "router2-net"],
			   # ["192.168.0.33",   4, "255.255.255.240",  "hw-net"],
			   # ["192.168.0.65",   5, "255.255.255.192",  "mgt-net"],
			   # ["192.168.255.9",  6, "255.255.255.252",  "office1-central"],
			   # ["192.168.255.5",  7, "255.255.255.252",  "office2-central"],
			   ["192.168.11.11",  8, "255.255.255.0",    "mynet"],
			]
  },
  
  :centralServer => {
	:box_name => "ubuntu/22.04",
	:vm_name  => "centralServer",
	:net => [
			   ["192.168.0.2",    2, "255.255.255.240",  "dir-net"],
			   ["192.168.11.12",  8, "255.255.255.0",    "mynet"],
			]
  },
  
 # :office1Router => {
        # :box_name => "ubuntu/22.04",
        # :vm_name => "office1Router",
        # :net => [
                   # ["192.168.255.10",  2,  "255.255.255.252",  "office1-central"],
                   # ["192.168.2.1",     3,  "255.255.255.192",  "dev1-net"],
                   # ["192.168.2.65",    4,  "255.255.255.192",  "test1-net"],
                   # ["192.168.2.129",   5,  "255.255.255.192",  "managers-net"],
                   # ["192.168.2.193",   6,  "255.255.255.192",  "office1-net"],
                   # ["192.168.11.20",   8,  "255.255.255.0",    "mynet"],
                # ]
  # },

  # :office1Server => {
        # :box_name => "ubuntu/22.04",
        # :vm_name => "office1Server",
        # :net => [
                   # ["192.168.2.130",  2,  "255.255.255.192",  "managers-net"],
                   # ["192.168.11.21",  8,  "255.255.255.0",    "mynet"],
                # ]
  # },

  # :office2Router => {
       # :box_name => "ubuntu/22.04",
       # :vm_name => "office2Router",
       # :net => [
                   # ["192.168.255.6",  2,  "255.255.255.252",  "office2-central"],
                   # ["192.168.1.1",    3,  "255.255.255.128",  "dev2-net"],
                   # ["192.168.1.129",  4,  "255.255.255.192",  "test2-net"],
                   # ["192.168.1.193",  5,  "255.255.255.192",  "office2-net"],
                   # ["192.168.11.30",  8,  "255.255.255.0",    "mynet"],
               # ]
  # },

  # :office2Server => {
       # :box_name => "ubuntu/22.04",
       # :vm_name => "office2Server",
       # :net => [
                  # ["192.168.1.2",    2,  "255.255.255.128",  "dev2-net"],
                  # ["192.168.11.31",  8,  "255.255.255.0",    "mynet"],
               # ]
  # }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|
        box.vm.box       = boxconfig[:box_name]
        box.vm.host_name = boxconfig[:vm_name]

	box.vm.provider "virtualbox" do |v|
            v.memory = 1536
            v.cpus   = 1
        end

        boxconfig[:net].each do |ipconf|
           box.vm.network("private_network", ip: ipconf[0], adapter: ipconf[1], netmask: ipconf[2], virtualbox__intnet: ipconf[3])
        end

        if boxconfig.key?(:public)
           box.vm.network "public_network", boxconfig[:public]
        end

#        if boxconfig.key?(:forwarded_port)
#           box.vm.network("forwarded_port", guest : 8080, host : 80)
  	   #box.vm.network "forwarded_port", guest : boxconfig[:forwarded_port], host : boxconfig[:forwarded_port]
  	   #box.vm.network "forwarded_port", boxconfig[:forwarded_port], boxconfig[:forwarded_port]
 #       end

        box.vm.provision "shell", inline: <<-SHELL
            mkdir -p ~root/.ssh
            cp ~vagrant/.ssh/auth* ~root/.ssh
            cat /vagrant/id_ed25519.pub >> /home/vagrant/.ssh/authorized_keys
	    cat /vagrant/id_ed25519.pub >> /root/.ssh/authorized_keys
	    timedatectl set-timezone Europe/Moscow
        SHELL
    end

  end
  
end