# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :master => {
        :box_name => "ubuntu/22.04",
        :ip_addr => '192.168.11.150'
  },
  :slave => {
        :box_name => "ubuntu/22.04",
        :ip_addr => '192.168.11.151'
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

         box.vm.box       = boxconfig[:box_name]
         box.vm.host_name = boxname.to_s

          #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset
          #box.vm.network "private_network", ip: boxconfig[:ip_addr]
	 box.vm.network("private_network", ip: boxconfig[:ip_addr], adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "mynet")

         box.vm.provider :virtualbox do |vb|
            #vb.customize ["modifyvm", :id, "--memory", "2048"]
   	      vb.memory = "2048"
	      vb.cpus   = "2"
            # Подключаем дополнительные диски
            #vb.customize ['createhd', '--filename', second_disk, '--format', 'VDI', '--size', 5 * 1024]
            #vb.customize ['storageattach', :id, '--storagectl', 'IDE', '--port', 0, '--device', 1, '--type', 'hdd', '--medium', second_disk]
         end

         #box.vm.provision :shell do |s|
         box.vm.provision "shell", inline: <<-SHELL
	   timedatectl set-timezone Europe/Moscow
	   mkdir -p ~root/.ssh
	   cp ~vagrant/.ssh/auth* ~root/.ssh
	   cat /vagrant/id_ed25519.pub >> /home/vagrant/.ssh/authorized_keys
	   cat /vagrant/id_ed25519.pub >> /root/.ssh/authorized_keys
         SHELL

      end
  end
end
