# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
    :hlvm => {
        :box_name => "bento/ubuntu-24.04",
        :ip_addr  => '192.168.11.101',
        :net_name => "mynet",

	:disks => {
		:sata1 => {
			:dfile => './sata1.vdi',
			:size => 10240, # Megabytes
			:port => 1
		},
		:sata2 => {
			:dfile => './sata2.vdi',
			:size => 2048,
			:port => 2
		},
		:sata3 => {
			:dfile => './sata3.vdi',
			:size => 1024,
			:port => 3
		},
		:sata4 => {
			:dfile => './sata4.vdi',
			:size => 1024, 
			:port => 4
		}
	}
  },
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box       = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s
          box.vm.network "private_network", ip: boxconfig[:ip_addr], virtualbox__intnet: boxconfig[:net_name]

          box.vm.provider :virtualbox do |vb|
                vb.customize ["modifyvm", :id, "--memory", "2048"]

			    boxconfig[:disks].each do |dname, dconf|
				  unless File.exist?(dconf[:dfile])
					vb.customize ['createhd', '--filename', dconf[:dfile], '--variant', 'Fixed', '--size', dconf[:size]]
				  end
		  end

		  boxconfig[:disks].each do |dname, dconf|
					 vb.customize ['storageattach', :id,  '--storagectl', 'SATA Controller', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]
		  end
      end
	  
 	  box.vm.provision "shell", inline: <<-SHELL
	      mkdir -p ~root/.ssh
              cp ~vagrant/.ssh/auth* ~root/.ssh
	      apt-get install -y mdadm smartmontools hdparm gdisk
	      timedatectl set-timezone Europe/Moscow
  	  SHELL
      end
  end
end

