---
- hosts: DynamicWeb
  become: yes 
  gather_facts: false

  tasks: 
  - name: Install packages
    ansible.builtin.apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
    with_items:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    tags:
      - docker

  - name: Add Docker s official GPG key
    ansible.builtin.apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
    tags:
      - docker

  - name: Verify that we have the key with the fingerprint
    ansible.builtin.apt_key:
      id: 0EBFCD88
      state: present
    tags:
      - docker

  - name: Set up the stable repository # добавляем репозиторий докера
    ansible.builtin.apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
      state: present
      update_cache: yes
    tags:
      - docker
  
  - name: Update apt packages
    ansible.builtin.apt:
      update_cache: yes
    tags:
      - docker

  - name: Install docker # установка докера
    ansible.builtin.apt:
      name: docker-ce
      state: present
      update_cache: yes
    tags:
      - docker

  - name: Add remote "vagrant" user to "docker" group
    ansible.builtin.user:
      name: vagrant
      group: "docker"
      groups: "docker"
      append: yes
    tags:
      - docker 

  - name: Install docker-compose 
    ansible.builtin.get_url:
      url : https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: 0777

  # Копируем проект с хост машины в созданную через vagrant
  - name: Copy project
    ansible.builtin.copy: 
      src: project
      dest: /home/vagrant

  # чтобы применились права на использование docker, необходимо перелогиниться
  - name: reset ssh connection
    ansible.builtin.meta: reset_connection

  - name: Run container
    ansible.builtin.shell:
      cmd: "docker-compose -f docker-compose.yml up -d"
      chdir: /home/vagrant/project/
